### ISSUE TITLE
Sign Up Button must be active only when all the criteria's are fulfilled

### ISSUE THREAD

**Issue by m1-key** [scorelab/senz#124]
Currently Sign Up button is active always , even though nothing is filled in the Sign Up form .
It would be great if it activates only when all the fields are correctly filled.

**Comment by m1-key** [comment]
I would like to work on this .

**Comment by m1-key** [comment]
I guess this issue is not required , as by default the Field will pop a message 'This field required to be filled' if it is empty and sign up button is clicked.

**Comment by m1-key** [comment]
> I guess this issue is not required , as by default the Field will pop a message 'This field required to be filled' if it is empty and sign up button is clicked.

I found it when I accidentally clicked the Sign UP button without filling one of the field. A snackbar appeared which shows a message that this field is required to be filled.

**Comment by kush-daga** [comment]
I guess so, but it took not a lot of changes to implement this, and it can be considered as an enhancement.

**Comment by m1-key** [comment]
Indeed
