### ISSUE TITLE
No need of password validation in Login Page

### ISSUE THREAD

**Issue by m1-key** [scorelab/senz#139]
Current version of the app supports password validation for login page , which is I guess is not at all required. Once the password has already been set and been verified during registration, then it need not be checked for verification at the time of login because it will be awkward to say to the user that your password is too short at the time of login.
Here validation means checking the password whether it satisfies the standard rules ( like containing an uppercase , lowercase , have a digit, and a special character) or not. Which is not necessary at the time of login to check. 
At the time of login, only email must be checked whether it is in right format or not , there is no need for checking password whether it is in right format or not.

**Comment by m1-key** [comment]
@sumedhe, @YashMeh  Sir, may I know why these two pull requests were closed , #140 and #137  ? Did they breached any guidelines or they are not required ?

**Comment by m1-key** [comment]
@YashMeh  Please can you tell me why the approved PR by you was closed ? As I am unable figure out the same. @YashMeh Please help

**Comment by YashMeh** [comment]
@sumedhe what was the issue ?

**Comment by sumedhe** [comment]
I think I got mixed up with the multiple PRs with the password input component. Thank you for informing the problem.
