### ISSUE TITLE
Login Button should only be active when email is valid and password is not null.

### ISSUE THREAD

**Issue by m1-key** [scorelab/senz#145]
Currently login button is active all the time.  It should be active only when fields are valid. i.e password is not null and email format is correct.

**Comment by YashMeh** [comment]
@m1-key I think it is better to have almost-same issues under one hood (It will make everyone's work easier.. :) ) .This issue could have been easily discussed under #124, just a heads-up for the next time. :)

**Comment by m1-key** [comment]
sure @YashMeh .
