### ISSUE TITLE
Create multiple accounts with a single email

### ISSUE THREAD

**Issue by shivam-sahu** [scorelab/senz#146]
**Describe the bug**
Single Email shouldn't be used to create multiple accounts.
**To Reproduce**
1. Go to create a new account and create a new account.
2. Now log out.
3. Now again create a new account with the previous email.

**Expected behavior**
A single email should create only one account. If a user has already created an account with that email the page should show "Email already exists " error.

**Screenshots**
here is ther screenshot of my database
![senz](https://user-images.githubusercontent.com/33172300/75626218-c47a1a00-5beb-11ea-9907-214e874c1d9b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser :Firefox

**Comment by shivam-sahu** [comment]
If this issue feels relevant then I like to work on it.

**Comment by YashMeh** [comment]
@shivam-sahu go ahead. :)
