### ISSUE TITLE
deleting or editing devices in all devices menu

### ISSUE THREAD

**Issue by shivam-sahu** [scorelab/senz#157]
**Is your feature request related to a problem? Please describe.**
Right now there is no feature of deleting or editing devices in all devices menu. If a person adds a device by mistake or entered wrong information there is no way to edit or delete it.

**Describe the solution you'd like**
I think there should be a button on the top like in the devices tab of the project menu to remove the device and a button on the right-hand side of each device to edit the device information.

**Additional context**
here is the rough idea of what I am thinking.....
![edit delete](https://user-images.githubusercontent.com/33172300/75922993-28ba0980-5e8a-11ea-8c20-c525ab8f4a4d.jpg)

**Comment by shivam-sahu** [comment]
@YashMeh @sumedhe If you think this feature is worth implementing then I can implement it.
And please share any suggestions or changes as you feel.

**Comment by YashMeh** [comment]
@shivam-sahu sure go ahead :+1:
