### ISSUE TITLE
Use toggle instead of a single switch button to turn on or off both devices and projects

### ISSUE THREAD

**Issue by carpecodeum** [scorelab/senz#162]
**Is your feature request related to a problem? Please describe.**
The current method is very cumbersome and buggy. As in the current system while in the devices tab when we select a device and then select another device it also gets selected and the both are switched on or off together.
<img width="1162" alt="Screenshot 2020-03-07 at 8 37 59 PM" src="https://user-images.githubusercontent.com/43586052/76145841-8f6e3b80-60b3-11ea-8d44-f086f1cbab40.png">

**Describe the solution you'd like**
Use toggle buttons for turning a device or a project on or off.

**Describe alternatives you've considered**
N/A

**Additional context**
working on it.

**Comment by carpecodeum** [comment]
@sumedhe @YashMeh i need some advice. as in the app these is a procedure to select multiple devices and then turn them on/off collectively which is quite buggy i am thinking on scrapping off that and using toggle switches for each one instead. how does that sound?

**Comment by YashMeh** [comment]
Sounds good to me, go ahead :+1:
