### ISSUE TITLE
provide the user with option to reset his password

### ISSUE THREAD

**Issue by AdityaSrivast** [scorelab/senz#169]
**Is your feature request related to a problem? Please describe.**
Currently if the user forgets his password, there is no way for him to recover his account

**Describe the solution you'd like**
Provide him with a mechanism to recover his account.

**Additional context**
I am working on this issue

**Comment by carpecodeum** [comment]
Hi @AdityaSrivast if you notice the backend for this feature already exist. All you have to do is provide a frontend gateway for the same. All the best!

**Comment by AdityaSrivast** [comment]
@carpecodeum Yeah I noticed it. Thanks for pointing out. :stars:

**Comment by AdityaSrivast** [comment]
Closing as merged at #172
