### ISSUE TITLE
Sample code for Java 

### ISSUE THREAD

**Issue by AdityaSrivast** [scorelab/senz#183]
**Is your feature request related to a problem? Please describe.**
There is no sample code for java. With the project aiming to move towards android applications, I feel java client should make things easier.

**Describe the solution you'd like**
Add sample code for java

**Additional context**
I'm working on this issue

**Comment by carpecodeum** [comment]
shouldn't this be incorporated as a milestone during gsoc? because I have included this as a milestone and not opened an issue because of that. please I would suggest you implement this during the gsoc coding period. :)

**Comment by AdityaSrivast** [comment]
@carpecodeum the gsoc milestone is to implement it for android devices. I have just made a client for java

**Comment by carpecodeum** [comment]
Okay! Thats good then.
